export enum SimulationEventType {
  BUG_DISCOVERED = 'BUG_DISCOVERED',
  SPRINT_DELAY = 'SPRINT_DELAY',
  DEVELOPER_BURNOUT = 'DEVELOPER_BURNOUT',
  CLIENT_REQUEST = 'CLIENT_REQUEST',
  PRIORITY_CHANGE = 'PRIORITY_CHANGE',
  INCIDENT = 'INCIDENT',
  TECHNICAL_DEBT_INCREASE = 'TECHNICAL_DEBT_INCREASE',
  DEVELOPER_DEPARTURE = 'DEVELOPER_DEPARTURE',
  SKILL_EVOLUTION = 'SKILL_EVOLUTION',
  RECRUITMENT_COMPLETED = 'RECRUITMENT_COMPLETED',
}

export enum DeveloperSeniority {
  JUNIOR = 'JUNIOR',
  MID = 'MID',
  SENIOR = 'SENIOR',
  LEAD = 'LEAD',
  PRINCIPAL = 'PRINCIPAL',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SprintStatus {
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TaskStatus {
  BACKLOG = 'BACKLOG',
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  DONE = 'DONE',
  BLOCKED = 'BLOCKED',
}

export enum BugSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
